kind: ConfigMap
apiVersion: v1
metadata:
  name: default-nginx
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: backend-logs
data:
  default.nginx.config: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            autoindex on;
        }
    }