apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-store
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.pv.fileStorage.path }}
  persistentVolumeReclaimPolicy: Retain
