package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'ScraperCore'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("ScraperCore")
    name = "scraper-core"
    url = "https://github.com/sergeytkachenko/scraper-core"
    authMethod = password {
        userName = "sergeytkachenko"
        password = "credentialsJSON:414a5929-5412-4bbe-bf25-84da1a3f8f70"
    }
}))

