# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:32000/scraper-backend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  host: app.elasticdata.io

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

pv:
  fileStorage:
    path: /opt/kubernetes/storage/fileStorage


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15

APP_VERSION: local
APP_LAST_UPDATED: "2020-02-05T21:47:00"

env:
  - name: SPRING_LOG_LEVEL
    value: INFO
  - name: GOOGLE_SIGNIN_CALLBACK_URL
    value: http://app.elasticdata.io/#/enter/
  - name: FACEBOOK_SIGNIN_CALLBACK_URL
    value: http://app.elasticdata.io/#/enter/

  - name: RABBITMQ_QUEUE_RUN_HOOKS
    value: PROD_RUN_HOOKS

  - name: RABBITMQ_RUN_TASK_EXCHANGE_NAME
    value: PROD_RUN_TASK
  - name: RABBITMQ_INBOX_FANOUT_EXCHANGE_NAME
    value: PROD_INBOX_FANOUT

  - name: RABBITMQ_RUN_TASK_ROUTING_KEY
    value: PROD_RUN_TASK
  - name: RABBITMQ_ROUTING_TASK_RUN
    value: PROD_RUN_HOOKS

  - name: ES_HOST_NAME
    value: elasticsearch-master.elasticsearch
  - name: ES_HTTP_PORT
    value: "9200"
  - name: ES_ENABLED
    value: "false"
  - name: PROXY_SERVICE_URL
    value: http://proxy
  - name: MINIO_URL
    value: https://storage.elasticdata.io
  - name: MINIO_PUBLIC_URL
    value: https://storage.elasticdata.io
  - name: MINIO_ACCESS_KEY
    value: elasticdataio
  - name: MINIO_SECRET_KEY
    value: wJalrXUtnFEMI/9874c97c907209cpuvpw97bpb/asdasdasdasdasd
