
env:
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_USER: "guest"
  MONGODB_PASSWORD: "guest"
  MONGODB_AUTH_DB: "admin"
  SPRING_LOG_LEVEL: ERROR
  SPRING_SERVER_PORT: "8080"
  GOOGLE_SIGNIN_CALLBACK_URL: http://app.elasticdata.io/#/enter/
  FACEBOOK_SIGNIN_CALLBACK_URL: http://app.elasticdata.io/#/enter/
  RABBITMQ_QUEUE_RUN_HOOKS: PROD_RUN_HOOKS
  RABBITMQ_RUN_TASK_EXCHANGE_NAME: PROD_RUN_TASK
  RABBITMQ_INBOX_FANOUT_EXCHANGE_NAME: PROD_INBOX_FANOUT
  RABBITMQ_RUN_TASK_ROUTING_KEY: PROD_RUN_TASK
  RABBITMQ_ROUTING_TASK_RUN: PROD_RUN_HOOKS
  ES_HOST_NAME: elasticsearch-master.elasticsearch
  ES_HTTP_PORT: "9200"
  ES_ENABLED: "false"
  PROXY_SERVICE_URL: http://proxy
  MINIO_URL: https://storage.elasticdata.io
  MINIO_PUBLIC_URL: https://storage.elasticdata.io
  MINIO_ACCESS_KEY: elasticdataio
  MINIO_SECRET_KEY: wJalrXUtnFEMI/9874c97c907209cpuvpw97bpb/asdasdasdasdasd
  PROXY_STATIC_URL: proxy
  WORKER_MANAGER_URL: https://app.elasticdata.io/worker-manager
  BOT_TELEGRAM_ENABLED: "false"