env:
  RABBITMQ_QUEUE_PIPELINE_RUN: PIPELINE_RUN_PROD
  RABBITMQ_QUEUE_PIPELINE_RUN_HIERARCHY: PIPELINE_RUN_HIERARCHY_PROD
  RABBITMQ_QUEUE_PIPELINE_STOP: PIPELINE_STOP_PROD
  RABBITMQ_QUEUE_PIPELINE_RUN_HOOKS: PIPELINE_RUN_HOOKS_PROD
  RABBITMQ_QUEUE_PIPELINE_FINISHED: PIPELINE_FINISHED_PROD