package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'ScraperService'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("ScraperService")) {
    vcs {
        add(DslContext.settingsRoot.id!!)
        add(RelativeId("ScraperCore"))
    }
}
