package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'ScraperService'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("ScraperService")) {
    vcs {
        add(DslContext.settingsRoot.id!!)
        add(RelativeId("ScraperCore"), "+:. => scraper-core")
    }

    expectSteps {
        script {
            name = "build"
            id = "RUNNER_2"
            scriptContent = "docker build"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_2"
            scriptContent = "sh docker/buildAndPublish.sh"
        }
    }
}
