package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '7e2530a1-6fbf-4607-8927-13b4d353b510'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("7e2530a1-6fbf-4607-8927-13b4d353b510"))

