= ElasticData.io - платформа автоматичного збору, трансформації і аналізу данних

== Про палатформу

ElasticData.io - це платформа, яка дає такі можливості:

* *Збирати данні з веб майданчиків*
** Користуючись API
** Використовуючи прості UI інструменти на сайті link:++http://app.elasticdata.io++[app.elasticdata.io]
* *Транформувати зібрані данні*
** Використовувати регулярні вирази для заміни тексту
** Додаткові функції для роботи с текстом
* *Аналізувати данні*
** Будувати різноманітні графіки, діаграмми використовуючи прості UI інструменти
** Будувати графіки обєднавши данні з різних сайтів
* *Спостерігати за зміною данних на веб сайтах*
** Підписатися на зміну данних
** Інтеграція по API
** Інтеграція через telegram bot
* *Публікація данних, або емуляція дій людини*
** Авторизація на сайті
** Підписка, лайки, коментарі, тощо
** Перепублікації статей
** Інше...

== Початок роботи

WARNING: Цей розділ в розробці

== Перелік інструкцій (команд) для збору данних

=== 1. Url - завантажити сторінку за url адресою

TIP: Команда *url* дозволяє завантажити будь-яку сторінку за вказаною веб адресою.

.Параметри команди url
[cols="a,a,a,a"]
|===
|*Назва параметру*
|*Опис*
|*Тип*
|*Значення за замовчуванням*

|urls
|Адреса web сторінки для переходу
|Array<String>
|Немає

|timeout
|Максимальний час очікування завантаження сторінки в секундах
|Number
|8

|source
|Стратегія отримання ссилок для переходу
|Object
|Немає
|===

.Приклак команди url в JSON форматі
====
[source,json]
----
{
    "cmd": "url", <1>
    "params": {
        "urls": ["https://google.com.ua"], <2>
        "timeout": 8 <3>
    }
}
----
<1> Назва команди
<2> Адреса web сторінки для переходу
<2> Максимальний час очікування завантаження сторінки в секундах (8 сек за замовчуванням)
====

=== 2. GetText - копіювання тексту з елементу, або атрибуту

TIP: Команда *getText* дозволяє скопіювати текс елемента, або будь який атрибут з елемента на сторінці.

.Приклад елемента на сторінці
====
[source,html]
----
<div id="app">
    <a class="logo" href="//site.com">site.com</a>
</div>
----
====

.Приклак конфігурації команди getText для #вибору тексту# в JSON форматі
====
[source,json]
----
{
    "cmd": "getText",
    "params": {
        "selector": "#app a.logo", <1>
        "key": "external_link", <2>
        "timeout": 4 <3>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано значення з елементу
<5> Максимальний час очікування елемента на сторінці

.Дані на виході (файл data.json)
[source,json]
----
[
    {
        "external_link": "site.com"
    }
]
----
====

.Приклак конфігурації команди getText для #вибору значення атрибуту# href в JSON форматі
====
[source,json]
----
{
    "cmd": "getText",
    "params": {
        "selector": "#app a.logo", <1>
        "key": "external_link", <2>
        "attribute": "href", <3>
        "prefix": "https:", <4>
        "timeout": 4 <5>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано значення з елементу
<3> Якщо вказано - буде копіювати значення вказанно атрибуту елементу (наприклад ```<a href=*"http://site.com"*>site.com</a>```)
<4> Якщо вказано - буде додано префікс-слово, до значення вибраних данних
<5> Максимальний час очікування елемента на сторінці

.Дані на виході (файл data.json)
[source,json]
----
[
    {
        "external_link": "https://site.com"
    }
]
----
====

=== 3. GetHtml - копіювання html з елементу

TIP: Команда *getHtml* дозволяє скопіювати html з елемента на сторінці.

.Приклад елемента на сторінці
====
[source,html]
----
<div id="app">
    <a class="logo" href="//site.com">site.com</a>
</div>
----
====

.Приклак конфігурації команди getHtml в JSON форматі
====
[source,json]
----
{
    "cmd": "getHtml",
    "params": {
        "selector": "#app", <1>
        "key": "app_html_text", <2>
        "timeout": 4 <3>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано html значення з елементу
<5> Максимальний час очікування елемента на сторінці

.Дані на виході (файл data.json)
[source,json]
----
[
    {
        "app_html_text": "<a class=\"logo\" href=\"//site.com\">site.com</a>"
    }
]
----
====

=== 4. GetUrl - копіювання поточної адреси сайту

TIP: Команда *getUrl* дозволяє скопіювати веб адресу поточної сторінки.

.Приклак конфігурації команди getUrl в JSON форматі
====
[source,json]
----
{
    "cmd": "url",
    "params": {
        "urls": ["http://google.com.ua"], <1>
    }
},
{
    "cmd": "getUrl",
    "params": {
        "key": "current_url", <2>
        "timeout": 4 <3>
    }
}
----
<1> Веб адреса сторінки, яку потрібно завантажити
<2> Назва ключа, куди буде скопійовано веб адресу поточної сторінки
<3> Максимальний час очікування

.Дані на виході (файл data.json)
[source,json]
----
[
    {
        "current_url": "http://google.com.ua"
    }
]
----
====

=== 5. PutText - вставити текст в елемент

TIP: Команда *putText* дозволяє вставити текст в елемент #<input /># або #<textarea />#.
Це може буди необхідно, наприклад при авторизації на сайті.

.Приклад елемента на сторінці, в який треба вставити текст
====
[source,html]
----
<form id="login">
    <input class="login" />
    <input id="password" type="password" />
    <button type="submit">login</button>
</div>
----
====


.Приклак конфігурації команди putText в JSON форматі
====
[source,json]
----
{
    "cmd": "putText",
    "params": {
        "selector": ".login", <1>
        "text": "supervisor", <2>
        "timeout": 3 <3>
    }
},
{
    "cmd": "putText",
    "params": {
        "selector": "#password",
        "text": "my_password"
    }
}
----
<1> CSS, або XPATH селектор елементу, в який необхідно вставити текст
<2> Текс який необхідно вставити
<3> Максимальний час очікування елемента на сторінці
====

=== 6. Click - javascript клік на елемент
=== 7. NativeClick - клік на елемент з наведенням курсору
=== 8. Навести курсор на елемент
=== 9. Виконати javascript на сторінці
=== 10. Цикл
=== 11. Умова
=== 12. Замінити текст
=== 13. Чекати зміни html на елементі
=== 14. Чекати зміни кількості елементів
=== 15. Чекати появи елемента на сторінці
=== 16. Переключити контекст на iframe
=== 17. Зробити скрішот екрану



