= ElasticData.io - платформа автоматичного збору, трансформації і аналізу данних


== Перелік інструкцій для збору данних

=== 1. Завантажити сторінку за url адресою

TIP: Команда *url* дозволяє завантажити будь-яку сторінку за вказаною веб адресою.

.Параметри команди url
[cols="a,a,a,a"]
|===
|*Назва параметру*
|*Опис*
|*Тип*
|*Значення за замовчуванням*

|urls
|Адреса web сторінки для переходу
|Array<String>
|Немає

|timeout
|Максимальний час очікування завантаження сторінки в секундах
|Number
|8
|===

.Приклак команди url
====
[source,json]
----
{
    "cmd": "url", <1>
    "params": {
        "urls": ["https://google.com.ua"], <2>
        "timeout": 8 <3>
    }
}
----
<1> Назва команди
<2> Адреса web сторінки для переходу
<2> Максимальний час очікування завантаження сторінки в секундах (8 сек за замовчуванням)
====

=== 2. Копіювання тексту з елементу, або атрибуту

TIP: Команда *getText* дозволяє скопіювати текс елемента, або будь який атрибут з елемента на сторінці.

.Приклад елемента на сторінці
====
[source,html]
----
<div id="app">
    <a class="logo" href="//site.com">site.com</a>
</div>
----
====

.Приклак конфігурації команди getText для #вибору тексту#
====
[source,json]
----
{
    "cmd": "getText",
    "params": {
        "selector": "#app a.logo", <1>
        "key": "external_link", <2>
        "timeout": 4 <3>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано значення з елементу
<5> Максимальний час очікування елемента на сторінці

.Дані на виході
[source,json]
----
[
    {
        "external_link": "site.com"
    }
]
----
====

.Приклак конфігурації команди getText для #вибору значення атрибуту# href
====
[source,json]
----
{
    "cmd": "getText",
    "params": {
        "selector": "#app a.logo", <1>
        "key": "external_link", <2>
        "attribute": "href", <3>
        "prefix": "https:", <4>
        "timeout": 4 <5>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано значення з елементу
<3> Якщо вказано - буде копіювати значення вказанно атрибуту елементу (наприклад ```<a href=*"http://site.com"*>site.com</a>```)
<4> Якщо вказано - буде додано префікс-слово, до значення вибраних данних
<5> Максимальний час очікування елемента на сторінці

.Дані на виході
[source,json]
----
[
    {
        "external_link": "https://site.com"
    }
]
----
====

=== 3. Копіювання html з елементу
=== 4. Копіювання поточної адреси сайту
=== 5. Вставити текст в елемент
=== 6. Javascript Клік на елемент
=== 7. Клік на елемент
=== 8. Навести курсор на елемент
=== 9. Виконати javascript на сторінці
=== 10. Цикл
=== 11. Умова
=== 12. Замінити текст
=== 13. Чекати зміни html на елементі
=== 14. Чекати зміни кількості елементів
=== 15. Чекати появи елемента на сторінці
=== 16. Переключити контекст на iframe
=== 17. Зробити скрішот екрану



