= ElasticData.io - платформа автоматичного збору, трансформації і аналізу данних


== Перелік інструкцій для збору данних

=== 1. Завантажити сторінку за url адресою

TIP: Команда *url* дозволяє завантажити будь-яку сторінку за вказаною веб адресою.

.Приклак команди url
====
[source,json]
----
{
    "cmd": "url", <1>
    "params": {
        "urls": ["http://google.com.ua"], <2>
        "timeout": 8 <3>
    }
}
----
<1> Назва команди
<2> Адреса web сторінки для переходу
<2> Максимальний час очікування завантаження сторінки в секундах (8 сек за замовчуванням)
====

=== 2. Копіювання тексту з елементу, або атрибуту

TIP: Команда *getText* дозволяє скопіювати текс, або атрибут з будь якого елемента на сторінці.

.Приклак команди getText
====
[source,json]
----
{
    "cmd": "getText",
    "params": {
        "selector": "h1.price", <1>
        "key": "price_usd" <2>
    },
    "cmd": "getText",
    "params": {
        "selector": ".logo",
        "key": "external_link",
        "attribute": "href" <3>
    }
}
----
<1> CSS, або XPATH селектор елементу
<2> Назва ключа, куди буде скопійовано начення з елементу
<3> Якщо вказано - буде копіювати значення вказанно атрибуту елементу, а не текст елементу
====

=== 3. Копіювання html з елементу
=== 4. Копіювання поточної адреси сайту
=== 5. Вставити текст в елемент
=== 6. Javascript Клік на елемент
=== 7. Клік на елемент
=== 8. Навести курсор на елемент
=== 9. Виконати javascript на сторінці
=== 10. Цикл
=== 11. Умова
=== 12. Замінити текст
=== 13. Чекати зміни html на елементі
=== 14. Чекати зміни кількості елементів
=== 15. Чекати появи елемента на сторінці
=== 16. Переключити контекст на iframe
=== 17. Зробити скрішот екрану



