[#api]
== Перелік доступних API викликів

* link:++#run-pipeline++[Запуск павука]
* link:++#pipeline-data++[Отримання данних]

[#run-pipeline]
=== 1. Запуск павука

==== Run. Параметри запуску павука

[cols="h,5a"]
|===
| URL
| domain - `https://app.elasticdata.io` +
path - `/api/pipeline/run/*[pipelineId]*` +
де *[pipelineId]* - id павука, який необхідно запустити

| Method
| POST

| Request Body
| include::dto/PipelineRunDto.adoc[]

| Response Body
| include::dto/PendingApiTaskDto.adoc[]
|===

IMPORTANT: Після завершення роботи задачі, на hookUrl адресу буде відправлено весь документ зі спарсеними данними.
З http заголовков `Content-Type: application/json`

[#pipeline-data]
=== 2. Отримання данних

Окрім hooks механізму з використанням параметру `hookUrl`, існує додаткова можливість отримати данні напряму через API.

==== Get data. Параметри отримання спарсених данних

[cols="h,5a"]
|===
| URL
| domain - `https://app.elasticdata.io` +
path - `/api/pipeline-task/data/*[taskId]*` +
де *[taskId]* - `id` задачі яке повернулося в Response Body із попереднього пункту *1. Запуск павука*

| Method
| GET

| Response Body
| parsed JSON document
|===

